Add check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -93,8 +93,17 @@ jobs:
           command: |
             cd ~/project/infra
             terraform init
-            DB_NAME=$(terraform output -raw rds_db_name)
-            echo "DB_NAME=$DB_NAME" >> $BASH_ENV
+            DB_NAME=$(terraform output -raw rds_db_name | sed 's/\x1b\[[0-9;]*m//g' | xargs)
+
+            # בדיקה אם המשתנה ריק
+            if [ -z "$DB_NAME" ]; then
+              echo "❌ Error: DB_NAME is empty or could not be extracted."
+              exit 1
+            fi
+
+echo "🔍 DB_NAME found: '$DB_NAME'"
+echo "DB_NAME=$DB_NAME" >> $BASH_ENV
+
       - run:
           name: Deploy RDS via Terraform
           command: |
